### PR TITLE
IMPORTANT FIX: Error in prism and reordered palettes for dropdown

### PR DESCRIPTION
**Pull request by makella**
@javisantana @rochoa @saleiva 

This is an important update for Builder!! I had a mistake in the default category palette `Prism` and also since we can't get the defaults for color by value in, I reordered the sequential palettes. I also removed two palettes that I haven't seen anyone use.

Can you please merge?

THANKS!!
mamata

### CODE REVIEW

**Comment by javisantana** [comment]
Hey, we can't remove paletes because we could break visualizations

**Comment by makella** [comment]
oops. ok, i will fix! sorry and thanks for telling me... now i know not to do that again!

**Comment by makella** [comment]
@javisantana ok i added back the two i deleted. 

thanks!
mamata

**Comment by rochoa** [comment]
Can we split this PR into two: one for the fix, and another one for the reordering. Even better, could we think in another way to order them, otherwise each time we want to change the order we would have this big changeset which is impossible to track/validate.

**Comment by makella** [comment]
@rochoa welcome back!

ok, i take your point, no problem.

so can i make one pull request for now that just fixes the default category palette `Prism` and then maybe next week we can discuss the reordering?

correcting Prism will fix this issue: https://github.com/CartoDB/cartodb/issues/10656

Ultimately, with the reordering, I am trying to accomplish a default palette for choropleth maps as described in this issue:

https://github.com/CartoDB/cartodb/issues/8820

let me know what you think is best

thanks!

**Comment by rochoa** [comment]
Hi @makella ! 😄 

It would be better if you split the `Prism` fix and the reordering.

And about the reordering I think we should fixed at the Builder level, not here. cc @xavijam.

**Comment by makella** [comment]
@rochoa @xavijam ok.

added a new PR for `Prism` fix.

Let's discuss more about the reordering because I agree. Depending on the geometry (point, line,poly) I would like to recommend a specific palette for defaults related to style > by value.

Let's definitely talk about how we can make it happen!

thanks!

**Pull request closed without merging**
