### PR TITLE
Discuss "To fix default category palette Prism"

### PR DESCRIPTION
**Pull request by rochoa**
This is #16, once again.

### CODE REVIEW

**Comment by rochoa** [comment]
@makella Why do we keep the gray color for 11 classes but we don't have gray colors in other cases?

What if I want to display only 4 categories, and make the rest of the categories into _Others_? The others, in that case, will get the next color in the ramp and not a neutral color, won't them?

What if tomorrow we want to add 12 classes, do we remove the gray/neutral color from the _11_ class, and we add it to the _12_?

**Comment by xavijam** [comment]
Adding myself to the loop before releasing anything.

**Comment by makella** [comment]
@rochoa hey!

this is a great question and one that I hadn't thought of. if we can define an 'other' color for all cases, that is ok with me.

but looking at the forms, I don't know how this would happen since we assign category ramps for a max of 11 categories.

if you have a suggestion on how to do this, please let me know and i will work on it.

the issue with the default `prism` ramp right now is that I had one extra color in there -- the super bright red. so instead of 'others' being assigned to the gray, they were getting assigned to that bright red.

**Comment by makella** [comment]
@xavijam i think this is a larger discussion and I don't think releasing this small fix will impact anything. this fix follows the same pattern that our other category ramps do.

but if you guys want to work on this issue before merging this small fix, that's ok with me.

**Comment by xavijam** [comment]
That's true (further to the forms limitation), because we don't provide the Others option unless there are more than 10 categories. But I agree with @rochoa that we should not get rid of the Others color for any ramp size, just in case user wants to use it for other purposes. What about we add the same `Other` color for any ramp? In short, the #555 color.

**Comment by xavijam** [comment]
Check my last changes @makella and @rochoa, all agree? It is basically the fix for Other color in any Prism ramp. Sounds good?

**Comment by makella** [comment]
@xavijam well, every ramp has its own other color. the 11th other color in every category ramp is a gray (or neutral color) that matches best with that ramp.

#555 will not look good with every ramp (trust me!) to illustrate, here is each category ramp with the 11 category variation. You'll notice that the 11th color varies from true gray to other shades that support a neutral backdrop to the more vivid color.

screen shot 2016-11-22 at 7 45 57 am

**Comment by makella** [comment]
@rochoa @xavijam i'm confused. let me take a closer look at the changes you are proposing

**Comment by xavijam** [comment]
Ok, take a look, but if you think that #555 color will not look good in every Prism ramp, let's choose the proper one and we will be ready to go. The thing here is release process takes some time and it is better to address this properly and only do it once.

**Comment by makella** [comment]
ok so i see what you did.

there are more category ramps than just `Prism`. There is `Bold`, `Vivid`, `Pastel`, `Safe`, `Antique` as well basically, we have 6 category ramps.

What you are proposing is ok with me. What needs to happen is that we need to take the `other` color from each of the other 5 category ramps and do the same.

does that make sense?

**Comment by makella** [comment]
@xavijam some more explanation (sorry!) I hope I am not being confusing.

the other color `#555` is ok for every variation of the `Prism` ramp.

But for example, the `Other` color for `Bold` should be `#A5AA99`

so basically, each 11th color for each of the 6 category ramps, needs to be added like you've done for Prism.

**Comment by makella** [comment]
@xavijam @rochoa I'll make the fixes we discussed last week. and make a new pull request with those changes

Just to make sure we want to do the following

- add one more color to each category ramp
- add the `other` color for each ramp inside the six unique category ramps

sound right?

**Comment by xavijam** [comment]
Fine by me!

**Pull request closed without merging**
